[project]
name = "bluerov-topside"
version = "0.2.0"
description = "Deployment software for the BlueROV topside computer"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyttsx3>=2.99",
    "setuptools",
]

[tool.uv]
python-preference = "only-system"

[tool.basedpyright]
typeCheckingMode = "standard"
enableTypeIgnoreComments = true
reportMissingTypeStubs = "none"
