# standard configuration looks something like,
#
# pcm.!default {
#     type hw
#     card 0
#     device 0
# }

# ctl.!default {
#     type hw
#     card 0
# }
#
# the following is for the onboard Intel PCH audio device (ALC289)
#
pcm.!default {
    type plug
    slave.pcm "hw:CARD=PCH,DEV=0"
}

ctl.!default {
    type hw
    card "PCH"
}
