# Copyright 2026, Evan Palmer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import importlib
from functools import reduce
from typing import Any

import rclpy
from mavros_msgs.msg import OverrideRCIn
from rclpy.node import Node
from rclpy.qos import qos_profile_system_default as qos
from sensor_msgs.msg import Joy
from std_srvs.srv import SetBool

# auto-generated by generate_parameter_library_py
from topside_teleop.router_parameters import router_interface


def rescale(value: float, min_val: float, max_val: float) -> float:
    return (((value + 1) * (max_val - min_val)) / 2.0) + min_val


def get_interface_type(type_name: str, interface_type: str):
    split_name = type_name.split("/")
    assert len(split_name) == 3, f"Invalid type_name '{type_name}'."
    package, interface, message = split_name
    if interface != interface_type:
        raise ValueError(f"Cannot use interface '{interface}' for an {interface_type}")
    module = importlib.import_module(package + "." + interface_type)
    return getattr(module, message)


def rgetattr(obj, attr, *args):
    def _getattr(obj, attr):
        return getattr(obj, attr, *args)

    return reduce(_getattr, [obj] + attr.split("."))


def rsetattr(obj, attr, val):
    pre, _, post = attr.rpartition(".")
    return setattr(rgetattr(obj, pre) if pre else obj, post, val)


class TeleopRouter(Node):
    """Message router for sending joystick commands to an external controller or to
    ArduSub."""

    def __init__(self):
        super().__init__("topside_teleop")

        self.param_listener = router_interface.ParamListener(self)
        self.params = self.param_listener.get_params()

        # keep track of whether or not we are sending joystick commands to the ArduSub
        #
        # this prevents flooding the controller/ArduSub with joystick commands when we
        # are using an autonomous mode
        self.send_to_ardusub = False

        self.rc_pub = self.create_publisher(OverrideRCIn, "/mavros/rc/override", qos)
        self.joy_sub = self.create_subscription(Joy, "/joy", self.rc_input_cb, qos)
        self.enable_srv = self.create_service(SetBool, "~/enable", self.enable_cb)

        # the external control interface allows us to send e.g. velocity commands to
        # a downstream controller instead of override commands to MAVROS
        if self.params.external_control.enable:
            self.external_interface = get_interface_type(
                self.params.external_control.interface_type, "msg"
            )
            self.external_pub = self.create_publisher(
                self.external_interface, self.params.external_control.topic, qos
            )
            self.scale_value = lambda x: rescale(
                x,
                self.params.external_control.min_value,
                self.params.external_control.max_value,
            )

        # normalize the PWM values to the provided range
        self.scale_pwm = lambda x: int(
            rescale(x, self.params.min_pwm, self.params.max_pwm)
        )

    def enable_cb(
        self, request: SetBool.Request, response: SetBool.Response
    ) -> SetBool.Response:
        """Enable/disable the joystick interface given the service request.

        Parameters
        ----------
        - `request`: A `SetBool` request, indicating whether to send joystick inputs to
            ArduSub or not.
        - `response`: A `SetBool` response, indicating the service result.

        Returns
        -------
        The `SetBool` service response.
        """
        self.send_to_ardusub = request.data
        if request.data:
            self.get_logger().info("Sending joystick input to MAVROS")
        else:
            self.get_logger().info("Stopping joystick input to MAVROS")

        response.success = True
        response.message = "Manual input " + ("enabled" if request.data else "disabled")
        return response

    def rc_input_cb(self, msg: Joy):
        """Route the incoming joystick commands.

        The joystick commands will either be sent to ArduSub or to the external
        controller (if one is enabled).

        Parameters
        ----------
        - `msg`: A `Joy` message with the current joystick commands.
        """
        if len(msg.axes) < 4:
            self.get_logger().error(
                "Received joystick message with insufficient axes. Expected 4, got "
                f"{len(msg.axes)}."
            )
            return

        # if we aren't sending the joystick inputs to ArduSub, that's because we are
        # either trying to send the messages to the external controller or because we
        # are in some autonomous mode.
        if not self.send_to_ardusub:
            if self.params.external_control.enable:
                external_msg = self.external_interface()

                controls = self.params.external_control.interface_controls
                for i, control in enumerate(controls):
                    rsetattr(external_msg, control, self.scale_value(msg.axes[i]))

                self.external_pub.publish(external_msg)
            return

        # default to no change for all channels
        rc_msg = OverrideRCIn()
        rc_msg.channels = [OverrideRCIn.CHAN_NOCHANGE] * 18

        rc_msg.channels[4] = self.scale_pwm(msg.axes[1])
        rc_msg.channels[5] = self.scale_pwm(-1 * msg.axes[0])
        rc_msg.channels[2] = self.scale_pwm(msg.axes[3])
        rc_msg.channels[3] = self.scale_pwm(-1 * msg.axes[2])

        self.rc_pub.publish(rc_msg)


def main(args: Any = None):
    rclpy.init(args=args)
    teleop_node = TeleopRouter()
    rclpy.spin(teleop_node)
    teleop_node.destroy_node()
    rclpy.shutdown()
