# standard configuration looks something like,
#
# pcm.!default {
#     type hw
#     card 0
#     device 0
# }

# ctl.!default {
#     type hw
#     card 0
# }
#
# the following is for my desktop
#
pcm.!default {
    type plug
    slave.pcm "hw:CARD=III,DEV=0"
}

ctl.!default {
    type hw
    card "III"
}