topside_watchdog:
    ros__parameters:
        notification_interval: 30.0 # seconds between repeated warnings

        battery_topics:
            - /mavros/battery

        pressure_topics:
            - /mavros/imu/static_pressure
            - /bme680/pressure

        battery_monitor_configurations:
            /mavros/battery:
                total_cells: 4
                cutoff: 0.25
                name: "Primary battery"

        pressure_monitor_configurations:
            /mavros/imu/static_pressure:
                minimum_pressure: 10.0 # psi
                name: "BlueROV bottle"

            /bme680/pressure:
                minimum_pressure: 10.0 # psi
                name: "Autonomy bottle"
