# Copyright 2026, Evan Palmer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from functools import partial
from typing import Any

import pyttsx3
import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_system_default as qos
from sensor_msgs.msg import BatteryState, FluidPressure

# auto-generated by generate_parameter_library_py
from topside_watchdog.watchdog_parameters import watchdog_interface

# the battery cells should never have a charge outside of this range. if it's higher,
# you are running the risk of a fire. if it's lower, you will damage the battery.
MIN_CELL_VOLTAGE = 3.0  # v
MAX_CELL_VOLTAGE = 4.2  # v

# Pascals to PSI conversion
PA_TO_PSI = 1 / 6894.76


class WatchDog(Node):
    """A simple watchdog used to monitor internal pressure and battery levels. Unlike
    its name suggests, this just performs monitoring (for now)."""

    def __init__(self):
        super().__init__("topside_watchdog")

        self.param_listener = watchdog_interface.ParamListener(self)
        self.params = self.param_listener.get_params()

        def notification_times(topics: list[str]) -> list[float | None]:
            return [None for _ in topics]

        # keep track of when the user (myself) was last notified of each warning, so that
        # an active warning can be repeated until it clears without spamming me in
        # between. `None` means that the monitor isn't currently warning about anything.
        self.battery_last_notified = notification_times(self.params.battery_topics)
        self.pressure_last_notified = notification_times(self.params.pressure_topics)

        # text-to-speech engine
        self.engine = pyttsx3.init()

        for i, topic in enumerate(self.params.battery_topics):
            cb = partial(self.battery_cb, topic, i)
            self.create_subscription(BatteryState, topic, cb, qos)

        for i, topic in enumerate(self.params.pressure_topics):
            cb = partial(self.pressure_cb, topic, i)
            self.create_subscription(FluidPressure, topic, cb, qos)

    def notify(self, last_notified: list[float | None], idx: int, message: str) -> None:
        """Announce a warning, repeating at most once per `notification_interval`.

        Parameters
        ----------
        - `last_notified`: The monitor's notification-time list, updated in place.
        - `idx`: The index within `last_notified` that this monitor stores its
            notification time at.
        - `message`: The notification to log and speak.
        """
        now = self.get_clock().now().nanoseconds * 1e-9
        last = last_notified[idx]

        if last is not None and now - last < self.params.notification_interval:
            return

        self.get_logger().warning(message)
        self.engine.say(message)
        self.engine.runAndWait()
        last_notified[idx] = now

    def battery_cb(self, topic: str, notification_idx: int, msg: BatteryState):
        """Notify users when a battery is low.

        Parameters
        ----------
        - `topic`: The battery topic: used to retrieve the monitor configurations.
        - `notification_idx`: The `battery_last_notified` index that this battery stores
            its notification time at.
        - `msg`: The `BatteryState` message.
        """
        configs = self.params.battery_monitor_configurations.get_entry(topic)

        max_charge = configs.total_cells * MAX_CELL_VOLTAGE
        min_charge = configs.total_cells * MIN_CELL_VOLTAGE

        current_charge = (msg.voltage - min_charge) / (max_charge - min_charge)

        if current_charge < configs.cutoff:
            self.notify(
                self.battery_last_notified,
                notification_idx,
                f"{configs.name} is low. Current charge is "
                f"{(current_charge * 100):.0f}%.",
            )
        else:
            self.battery_last_notified[notification_idx] = None

    def pressure_cb(self, topic: str, notification_idx: int, msg: FluidPressure):
        """Notify users when a bottle has lost vacuum.

        Parameters
        ----------
        - `topic`: The pressure topic: used to retrieve the monitor configurations.
        - `notification_idx`: The `pressure_last_notified` index that this sensor stores
            its notification time at.
        - `msg`: The `FluidPressure` message.
        """
        configs = self.params.pressure_monitor_configurations.get_entry(topic)
        current_pressure = msg.fluid_pressure * PA_TO_PSI

        if current_pressure > configs.minimum_pressure:
            notified = self.pressure_notifications[notification_idx]
            if not notified:
                notification = (
                    f"{configs.name} has lost vacuum. Current pressure is "
                    f"{current_pressure:.1f} psi."
                )

                self.get_logger().info(notification)
                self.engine.say(notification)
                self.engine.runAndWait()
                self.pressure_notifications[notification_idx] = True


def main(args: Any = None):
    rclpy.init(args=args)
    teleop_node = WatchDog()
    rclpy.spin(teleop_node)
    teleop_node.destroy_node()
    rclpy.shutdown()
