# Copyright 2026, Evan Palmer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from typing import Any

import pyttsx3
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import BatteryState, FluidPressure

# auto-generated by generate_parameter_library_py
from topside_watchdog.watchdog_parameters import watchdog_interface

# the battery cells should never have a charge outside of this range. if it's higher,
# you are running the risk of a fire. if it's lower, you will damage the battery.
MIN_CELL_VOLTAGE = 3.0  # v
MAX_CELL_VOLTAGE = 4.2  # v

# Pascals to PSI conversion
PA_TO_PSI = 1 / 6894.76


class WatchDog(Node):
    """A simple watchdog used to monitor internal pressure and battery levels. Unlike
    its name suggests, this is just performs monitoring (for now)."""

    def __init__(self):
        super().__init__("topside_watchdog")

        self.param_listener = watchdog_interface.ParamListener(self)
        self.params = self.param_listener.get_params()

        def notification_list(topics: list[str]):
            return [False for _ in range(len(topics))]

        # keep track of whether or not the user (myself) was notified of the warning.
        # (I don't want to spam myself with a bunch of messages; I'll just get pissed)
        self.battery_notifications = notification_list(self.params.battery_topics)
        self.pressure_notifications = notification_list(self.params.pressure_topics)

        # text-to-speech engine
        self.engine = pyttsx3.init()

    def battery_cb(self, topic: str, notification_idx: int, msg: BatteryState):
        """Notify users when a battery is low.

        Parameters
        ----------
        - `topic`: The battery topic; used to retrieve the monitor configurations.
        - `notification_idx`: The `battery_notifications` index that this battery stores
            its notification flag at.
        - `msg`: The `BatteryState` message.
        """
        configs = self.params.battery_monitor_configurations.get_entry(topic)

        max_charge = configs.total_cells * MAX_CELL_VOLTAGE
        min_charge = configs.total_cells * MIN_CELL_VOLTAGE

        current_charge = msg.voltage - min_charge / max_charge - min_charge

        if current_charge < configs.cutoff:
            notified = self.battery_notifications[notification_idx]
            if not notified:
                notification = (
                    f"{configs.name} is low. Current charge is "
                    f"{current_charge * 100}\\%."
                )

                self.get_logger().info(notification)
                self.engine.say(notification)

    def pressure_cb(self, topic: str, notification_idx: int, msg: FluidPressure):
        """Notify users when the internal pressure is low.

        Parameters
        ----------
        - `topic`: The pressure topic; used to retrieve the monitor configurations.
        - `notification_idx`: The `pressure_notifications` index that this sensor stores
            its notification flag at.
        - `msg`: The `FluidPressure` message.
        """
        configs = self.params.pressure_monitor_configurations.get_entry(topic)
        current_pressure = msg.fluid_pressure * PA_TO_PSI

        if current_pressure < configs.minimum_pressure:
            notified = self.pressure_notifications[notification_idx]
            if not notified:
                notification = (
                    f"{configs.name} is low. Current pressure is "
                    f"{current_pressure} psi."
                )

                self.get_logger().info(notification)
                self.engine.say(notification)


def main(args: Any = None):
    rclpy.init(args=args)
    teleop_node = WatchDog()
    rclpy.spin(teleop_node)
    teleop_node.destroy_node()
    rclpy.shutdown()
