name: ROS

on:
  push:
    branches:
      - main
    paths:
      - ros/**
      - .github/workflows/ros.yml
  pull_request:
    paths:
      - ros/**
      - .github/workflows/ros.yml
  workflow_dispatch:

jobs:
  test:
    name: Build topside workspace
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: lyrical
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run ROS Industrial CI
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.env.ROS_DISTRO }}
          CXXFLAGS: -Wall -Wextra -Wpedantic -std=c++20
          TARGET_WORKSPACE: ros
